# Generated by Django 4.1.7 on 2023-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
